!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 128
  - - ent_coef
    - 0.0
  - - frame_stack
    - 4
  - - gae_lambda
    - 0.8
  - - gamma
    - 0.95
  - - learning_rate
    - 0.0001
  - - max_grad_norm
    - 0.5
  - - n_envs
    - 8
  - - n_epochs
    - 20
  - - n_steps
    - 512
  - - n_timesteps
    - 1000000000.0
  - - policy
    - CnnPolicy
  - - policy_kwargs
    - dict(activation_fn=nn.ReLU, net_arch=[dict(pi=[256, 512, 512, 256], vf=[256,
      512, 512, 256])] )
  - - sde_sample_freq
    - 4
  - - vf_coef
    - 0.5
